[shell]
program = "/bin/zsh"

[window]
blur = true

[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
italic = { family = "Inconsolata", style = "Italic" }
bold_italic = { family = "Inconsolata", style = "Bold Italic" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[terminal]
osc52 = "CopyPaste"
